import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Target, Users, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SectionHeading } from "@/components/shared";
import home from "@/assets/finchnet-home.jpeg.asset.json";

const title = "About Finchnet Ventures | Connectivity Partner";
const description = "Learn how Finchnet Ventures approaches residential connectivity, networking infrastructure, and professional installation.";
export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/about" }] }), component: Page });
const values = [[Target, "Tailored solutions", "Start with actual requirements, not assumptions."], [Wrench, "Professional installation", "Keep infrastructure organized and maintainable."], [Users, "Customer focus", "Explain options clearly and design around the people using them."], [CheckCircle2, "Core capability", "Residential internet, networks, security, cabling, and communications."]] as const;
function Page() { return <><PageHero eyebrow="About Finchnet Ventures" title="Connecting People, Properties, and Possibilities." text="A networking provider focused on residential connectivity and customized infrastructure shaped around real property requirements." image={home.url} /><section className="py-20"><div className="site-container grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Our mission" title="Make Modern Connectivity More Practical" text="Our mission is to help homes, properties, and organizations build dependable connections through considered planning, suitable infrastructure, and professional installation." /><Button asChild size="lg" className="mt-8"><Link to="/contact">Start a conversation <ArrowRight /></Link></Button></div><div className="grid gap-4">{values.map(([Icon, heading, text]) => <article key={heading} className="flex gap-5 border border-border p-6"><Icon className="mt-1 size-6 shrink-0 text-blue" /><div><h2 className="font-extrabold">{heading}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div></article>)}</div></div></section><section className="bg-secondary py-20"><div className="site-container"><SectionHeading eyebrow="Company information" title="Details Ready for Client Confirmation" text="This section is intentionally prepared for verified registration details, business contacts, operating locations, leadership information, and approved company history when supplied." /><div className="mt-10 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">{["Registered business name", "Registration details", "Primary office", "Approved company profile"].map((item) => <div key={item} className="bg-background p-6"><p className="text-xs font-bold uppercase tracking-[.12em] text-muted-foreground">{item}</p><p className="mt-4 font-extrabold">To be confirmed</p></div>)}</div></div></section></>; }