import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Eye, KeyRound, LockKeyhole, Router, ShieldCheck, Wifi } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SectionHeading } from "@/components/shared";
import technician from "@/assets/finchnet-technician.jpeg.asset.json";

export const Route=createFileRoute("/network-security")({head:()=>({meta:meta("Network Security Solutions | Finchnet Ventures","Security-conscious network planning, wireless security, access management, monitoring considerations, and VPN solutions."),links:[{rel:"canonical",href:"/network-security"}]}),component:Page});
function meta(title:string,description:string){return [{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}
const items=[[ShieldCheck,"Security planning","Consider security requirements while shaping the wider network."],[Router,"Secure configurations","Configure network equipment around suitable access and usage needs."],[Wifi,"Wireless security","Plan wireless access with thoughtful separation and credentials."],[KeyRound,"Access management","Support deliberate control over who can reach network resources."],[Eye,"Monitoring considerations","Identify practical visibility requirements for ongoing operations."],[LockKeyhole,"VPN solutions","Explore secure remote connectivity based on organizational needs."]];
function Page(){return <><PageHero eyebrow="Network security" title="Security Considered at Every Connection." text="Thoughtful planning and secure configurations help reduce avoidable exposure while keeping the network practical for the people who use it." image={technician.url}/><section className="py-20"><div className="site-container"><SectionHeading eyebrow="A considered approach" title="Build Security Into the Infrastructure" text="Services are scoped to the property and requirements. No network can be represented as universally protected or risk-free."/><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{items.map(([Icon,title,text])=>{const I=Icon as typeof Eye;return <article key={title as string} className="border-t-2 border-blue bg-secondary p-7"><I className="size-7 text-blue"/><h2 className="mt-7 text-xl font-extrabold">{title as string}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{text as string}</p></article>})}</div><Button asChild size="lg" className="mt-10"><Link to="/contact">Request a security consultation <ArrowRight/></Link></Button></div></section></>}