import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, ProcessSteps, QuoteBanner, SectionHeading } from "@/components/shared";
import { propertyTypes } from "@/lib/site-data";
import home from "@/assets/finchnet-home.jpeg.asset.json";
import technician from "@/assets/finchnet-technician.jpeg.asset.json";

export const Route = createFileRoute("/residential-internet")({ head: () => ({ meta: meta("Residential Internet | Finchnet Ventures", "Internet packages and professionally planned connectivity for homes, apartments, estates, and multi-unit developments."), links: [{ rel: "canonical", href: "/residential-internet" }] }), component: Residential });
function meta(title:string,description:string){return [{title},{name:"description",content:description},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}
function Residential(){return <><PageHero eyebrow="Connected living" title="Reliable Internet for Every Residential Unit." text="Clear package choices and professionally planned installation for individual homes, apartments, estates, and multi-unit developments." image={home.url}/><section className="py-20"><div className="site-container"><SectionHeading eyebrow="How it works" title="A Clear Path to Getting Connected"/><ProcessSteps steps={["Choose your package","Submit an installation request","Property and cabling assessment","Professional setup","Connect and enjoy your service"]}/></div></section><section className="bg-secondary py-20"><div className="site-container grid items-center gap-12 lg:grid-cols-2"><img src={technician.url} alt="Technician connecting Cat6 cables inside a network cabinet" className="aspect-[4/3] w-full object-cover"/><div><SectionHeading eyebrow="Installation and setup" title="Organized From the First Cable" text="Where required and approved for the site, the setup may include a mounted meter box, network switch placement, Cat6 routing through available conduits, and connection testing."/><p className="mt-6 border-l-2 border-cyan pl-5 text-sm leading-7 text-muted-foreground">Actual installation depends on property conditions, site assessment, permissions, and approved requirements.</p></div></div></section><section className="py-20"><div className="site-container"><SectionHeading eyebrow="Property solutions" title="Connectivity for Every Residential Setting"/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{propertyTypes.map((p)=>{const Icon=p.icon;return <article key={p.title} className="border border-border p-6"><Icon className="size-7 text-blue"/><h2 className="mt-7 text-lg font-extrabold">{p.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{p.text}</p></article>})}</div><Button asChild size="lg" className="mt-10"><Link to="/contact">Request a property solution <ArrowRight/></Link></Button></div></section><QuoteBanner/></>}