import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, QuoteBanner, SectionHeading } from "@/components/shared";
import { services } from "@/lib/site-data";
import technician from "@/assets/finchnet-technician.jpeg.asset.json";

export const Route = createFileRoute("/services")({ head: () => ({ meta: meta("Connectivity Services | Finchnet Ventures", "Explore residential internet, network infrastructure, security, cabling, access control, VoIP, and communication solutions."), links: [{ rel: "canonical", href: "/services" }] }), component: Services });
function meta(title: string, description: string) { return [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }]; }
function Services() { return <><PageHero eyebrow="Our capabilities" title="Complete Connectivity, Built Around You." text="From a single home connection to organized infrastructure across a development, our services adapt to the environment and its operational needs." image={technician.url} /><section className="py-20 md:py-28"><div className="site-container"><SectionHeading eyebrow="Nine core services" title="One Partner Across the Network" text="Each engagement begins with requirements, property conditions, and intended use—not an off-the-shelf assumption." /><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map((s, i) => { const Icon=s.icon; return <article key={s.title} className="flex flex-col border border-border bg-card p-7"><div className="flex items-center justify-between"><Icon className="size-8 text-blue"/><span className="text-xs font-extrabold text-muted-foreground">0{i+1}</span></div><h2 className="mt-8 text-xl font-extrabold">{s.title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{s.description}</p><h3 className="mt-6 text-xs font-extrabold uppercase tracking-[0.14em] text-blue">Typical value</h3><ul className="mt-3 grid gap-2 text-sm"><li className="flex gap-2"><Check className="size-4 text-blue"/>Planned for the site</li><li className="flex gap-2"><Check className="size-4 text-blue"/>Professionally organized</li><li className="flex gap-2"><Check className="size-4 text-blue"/>Room to adapt later</li></ul><Button asChild variant="outline" className="mt-8 self-start"><Link to={s.href}>Learn more <ArrowRight /></Link></Button></article>})}</div></div></section><QuoteBanner /></>; }