import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Headphones, MessagesSquare, PhoneCall, Route as RouteIcon, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHero, SectionHeading } from "@/components/shared";
import communications from "@/assets/finchnet-communications.jpeg.asset.json";

const title = "Unified Communications | Finchnet Ventures";
const description = "Unified communications, VoIP, call center systems, and communication workflow planning for organizations.";
export const Route = createFileRoute("/unified-communications")({ head: () => ({ meta: [{ title }, { name: "description", content: description }, { property: "og:title", content: title }, { property: "og:description", content: description }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/unified-communications" }] }), component: Page });
const capabilities = [[MessagesSquare, "Unified communication systems", "Bring communication channels into a clearer, more coordinated operating environment."], [PhoneCall, "VoIP solutions", "Explore flexible voice-over-IP options shaped around business workflows and cost considerations."], [Headphones, "Call center solutions", "Plan communication infrastructure around service teams and operational requirements."], [RouteIcon, "Workflow planning", "Map how calls and communication move through teams before selecting a solution."], [Users, "Scalable infrastructure", "Build around current users while allowing room for organizational change."]] as const;
function Page() { return <><PageHero eyebrow="Business communication" title="Bring Every Conversation Into Focus." text="Communication systems planned around how your teams work—across voice, customer service, collaboration, and future growth." image={communications.url} /><section className="py-20"><div className="site-container"><SectionHeading eyebrow="Connected teams" title="A Clearer Communication Environment" text="Specific equipment, integrations, pricing, and system capabilities will be defined after requirements are confirmed." /><div className="mt-12 grid gap-6 md:grid-cols-2">{capabilities.map(([Icon, heading, text], i) => <article key={heading} className={`p-8 ${i === 0 ? "bg-primary text-primary-foreground" : "border border-border bg-card"}`}><Icon className={`size-8 ${i === 0 ? "text-cyan" : "text-blue"}`} /><h2 className="mt-8 text-2xl font-extrabold">{heading}</h2><p className={`mt-4 leading-7 ${i === 0 ? "text-primary-foreground/70" : "text-muted-foreground"}`}>{text}</p></article>)}</div><div className="mt-12 grid gap-6 bg-secondary p-8 md:grid-cols-2 md:p-12"><div><p className="text-xs font-extrabold uppercase tracking-[.15em] text-blue">VoIP-ready space</p><h2 className="mt-4 text-2xl font-extrabold">Offerings can grow with the business.</h2></div><p className="leading-7 text-muted-foreground">This page leaves clear room for final VoIP packages, call-center equipment, integrations, and commercial terms once supplied.</p></div><Button asChild size="lg" className="mt-10"><Link to="/contact">Request a communication quote <ArrowRight /></Link></Button></div></section></>; }